version: '3.7'
volumes:
    database:
services:
    db:
        image: mysql:latest
        container_name: user-mysql
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=orion-user-service
            - MYSQL_DATABASE=orion-user-service
            - MYSQL_USER=orion-user-service
            - MYSQL_PASSWORD=orion-user-service
    phpMyAdmin:
            image: phpmyadmin/phpmyadmin:latest
            container_name: user-phpmyadmin
            environment:
                - PMA_ARBITRARY=1
            links:
                - db
            ports:
                - 80:80
            volumes:
                - /sessions

    service:
            # image: rodrigoprestesmachado/orion-talk-image:version-0.1
            build: .
            container_name: user-service
            ports:
                - 9080:9080
                - 9443:9443